### ISSUE TITLE
banner-card-title selector is broken for not-done missions

### ISSUE THREAD

**Issue by markus-hh** [erikchristiansson/bannergress-kml-export#1]
Hi!

The banner-card-title selector is broken for not-done missions.

Currently used selector: `#root > section > section > div > div > div > div.banner-info-with-map > div.banner-info.banner-info-left-pane-info > div > div > div.banner-card.list-style-done > div.banner-card-title`

Selector for not-done mission titles: `#root > section > section > div > div > div > div.banner-info-with-map > div.banner-info.banner-info-left-pane-info > div > div > div.banner-card.list-style-none > div.banner-card-title`

Note the difference in list-style-none vs list-style-done. A more robust selector would be `div.banner-card-title` (I tested that the export works this way)

Kind regards

**Comment by erikchristiansson** [comment]
Thanks! The script has been updated.
